---

- hosts: localhost
  gather_facts: true
  connection: local

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_vars_module.html#include-vars-load-variables-from-files-dynamically-within-a-task
# include_vars Loads YAML/JSON variables dynamically from a file or directory, recursively, during task runtime 
  tasks:
    - include_vars:
        file: ./global_variable.yml
    - include_role:
        name: cisco_live_prepare_for_device_onboarding
    - include_role:
        name: device_onboarding
    - include_role:
        name: obtain_cdg_info
    - include_vars:
        file: ./global_variable.yml
    - include_role:
        name: attach_device_to_cdg  